### ISSUE TITLE
Wiki auf Github

### ISSUE THREAD

**Issue by LaurenzG** [htl-leonding/2016_TuV3r#11]
Bis 16.06.2016

Projektphasen und Diagramme von dem Projekt

**Comment by ghost** [comment]
Projektteam-Page added

**Comment by ghost** [comment]
Footer added

**Comment by ghost** [comment]
Project team page updated

**Comment by ghost** [comment]
Create a new tournament page created

**Comment by ghost** [comment]
Changed the language to english
